<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\CoBrMaxMacro.Domain\CoBrMaxMacro.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Characters\Selection\Commands\v1\" />
    <Folder Include="Dungeons\Commands\v1\" />
    <Folder Include="Dungeons\Models\v1\" />
    <Folder Include="Dungeons\Queries\v1\" />
    <Folder Include="World\Navigation\" />
  </ItemGroup>

</Project>
